#!/bin/zsh

if [ x"$HOME" = x ] ; then
        export HOME=$(cd ~ ; pwd)
fi

if [ x"$HOSTNAME" = x ] ; then
        export HOSTNAME=$(hostname)
fi

export EMAIL="ales.zoulek@gmail.com"
export FULLNAME="Ales Zoulek"

export EDITOR=vim
export VISUAL=vim
export PAGER=less
export PYTHONSTARTUP=~/.pythonrc

export INPUTRC="~/.inputrc"

if [ $UID -eq 0 ]; then
        PATH=~root/bin:$PATH
else
        PATH="${HOME}/bin:${PATH}:/usr/local/bin:/usr/bin/vendor_perl"
fi

export PATH

# less options
export LESS=FRSX
export PAGER="less -$LESS"

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'


export GIT_MERGE_AUTOEDIT=no
